services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - database_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - database_data:/app/data
    depends_on:
      - backend

volumes:
  database_data: